using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System;
using UnityEngine.SceneManagement;

namespace Game.Menu
{
    /// <summary>
    /// World creation menu - handles creating new worlds with name and seed
    /// Integrated with SaveLoadService and WorldPersistenceManager
    /// Uses single long seed input that gets split into 3 parts internally
    /// </summary>
    public class WorldCreateUI : MonoBehaviour
    {
        [Header("UI Elements")]
        [SerializeField] private TMP_InputField worldNameInput;
        [SerializeField] private TMP_InputField seedInput;
        [SerializeField] private Button createButton;
        [SerializeField] private Button cancelButton;
        [SerializeField] private Button randomSeedButton;
        
        [Header("Configuration")]
        [SerializeField] private SeedConfig seedConfig;
        [SerializeField] private WorldPersistenceManager worldPersistence;

        [Header("Validation")]
        [SerializeField] private TextMeshProUGUI errorText;

        [Header("References")]
        [SerializeField] private WorldSelectionUI worldSelectionUI;
        [SerializeField] private SaveLoadService saveLoadService;
        
        [Header("Debug")]
        [SerializeField] private bool enableDebug = false;
        

        private void Start()
        {
            // Validate references
            if (saveLoadService == null)
            {
                saveLoadService = SaveLoadService.Instance;
                if (saveLoadService == null)
                {
                    Debug.LogError("[WorldCreateUI] SaveLoadService not available!");
                }
            }
            
            // Setup button listeners
            createButton.onClick.AddListener(OnCreateClicked);
            cancelButton.onClick.AddListener(OnCancelClicked);
            
            if (randomSeedButton != null)
            {
                randomSeedButton.onClick.AddListener(OnRandomSeedClicked);
            }

            if (worldSelectionUI == null)
            {
                worldSelectionUI = FindFirstObjectByType<WorldSelectionUI>();
            }

            // Clear error text on start
            if (errorText != null)
            {
                errorText.gameObject.SetActive(false);
            }
            
            // Set placeholders based on config
            if (seedConfig != null)
            {
                SetSeedPlaceholders();
            }

            // Set default random seed
            GenerateRandomSeed();
        }

        private void OnDestroy()
        {
            // Clean up listeners
            createButton.onClick.RemoveListener(OnCreateClicked);
            cancelButton.onClick.RemoveListener(OnCancelClicked);
            
            if (randomSeedButton != null)
            {
                randomSeedButton.onClick.RemoveListener(OnRandomSeedClicked);
            }
        }

        private void OnEnable()
        {
            // Reset fields when opening
            if (worldNameInput != null)
            {
                worldNameInput.text = "";
            }
            
            GenerateRandomSeed();

            if (errorText != null)
            {
                errorText.gameObject.SetActive(false);
            }

            // Focus on world name input
            if (worldNameInput != null)
            {
                worldNameInput.Select();
                worldNameInput.ActivateInputField();
            }
        }
        
        private void SetSeedPlaceholders()
        {
            if (seedInput != null && seedConfig != null)
            {
                int totalDigits = seedConfig.seed1DigitCount + seedConfig.seed2DigitCount + seedConfig.seed3DigitCount;
                seedInput.placeholder.GetComponent<TMP_Text>().text = new string('0', totalDigits);
            }
        }

        private void OnCreateClicked()
        {
            if (!ValidateInput())
            {
                return;
            }
            
            if (saveLoadService == null)
            {
                ShowError("Save service not available. Please restart the game.");
                return;
            }

            string worldName = worldNameInput.text.Trim();
            
            // Get full seed (empty will be auto-generated by SeedData constructor)
            string fullSeed = seedInput != null ? seedInput.text : "";
            
            // Create seed data (will auto-generate if empty, or split the provided long seed)
            SeedData seedData = new SeedData(fullSeed, seedConfig);
            
            if (enableDebug) Debug.Log($"Creating world: {worldName}");
            if (enableDebug) Debug.Log($"Seed: {seedData.seed1}-{seedData.seed2}-{seedData.seed3}");

            // Create world through save system
            WorldSaveData newWorld = saveLoadService.CreateNewWorld(worldName, seedData);
            
            if (newWorld == null)
            {
                ShowError("Failed to create world. Please try again.");
                return;
            }

            // Prepare world persistence for scene transition
            if (worldPersistence != null)
            {
                worldPersistence.PrepareNewWorld(worldName, seedData, newWorld.worldGuid);
            }
            else
            {
                Debug.LogError("[WorldCreateUI] WorldPersistenceManager not assigned!");
            }

            // Refresh world list in selection UI
            if (worldSelectionUI != null)
            {
                worldSelectionUI.RefreshWorldList();
            }
            
            // Return to world selection and auto-select the newly created world
            if (enableDebug) Debug.Log($"World created successfully: {worldName}");
            
            if (worldSelectionUI != null)
            {
                worldSelectionUI.ShowWorldSelection(true);
                // Auto-select the newly created world so player can immediately load it
                worldSelectionUI.SelectWorldByGuid(newWorld.worldGuid);
            }
            
            gameObject.SetActive(false);
        }

        private void OnCancelClicked()
        {
            if (enableDebug) Debug.Log("Cancel world creation");
            
            if (worldSelectionUI != null)
            {
                worldSelectionUI.ShowWorldSelection(true);
            }
            
            gameObject.SetActive(false);
        }

        private void OnRandomSeedClicked()
        {
            GenerateRandomSeed();
        }

        private void GenerateRandomSeed()
        {
            if (seedConfig == null)
            {
                Debug.LogWarning("[WorldCreateUI] SeedConfig not assigned!");
                return;
            }
            
            // Generate random seed as a complete long string
            string randomSeed = SeedData.GenerateRandomSeed(seedConfig);
            
            if (seedInput != null)
                seedInput.text = randomSeed;
        }

        private bool ValidateInput()
        {
            // Check if world name is empty
            if (string.IsNullOrWhiteSpace(worldNameInput.text))
            {
                ShowError("Please enter a world name");
                return false;
            }

            // Check if world name is too long
            if (worldNameInput.text.Trim().Length > 50)
            {
                ShowError("World name is too long (max 50 characters)");
                return false;
            }

            // Additional validation can be added here
            // For example: check if world name already exists

            return true;
        }

        private void ShowError(string message)
        {
            if (errorText != null)
            {
                errorText.text = message;
                errorText.gameObject.SetActive(true);
            }
            Debug.LogWarning($"World creation error: {message}");
        }
    }
}
